images:
  - name: quicklookup/ctxllm
    newTag: 95a2104

resources:
  - ../../base
patches:
  - path: ctxllm-config.yaml
  - target:
      kind: Ingress
      name: ctxllm
    patch: |
      - "op": replace
        "path": /spec/rules/0/host
        "value": &fqdn llm.contextsuite.dev
      - "op": replace
        "path": /spec/tls/0/hosts/0
        "value": *fqdn  # <- this is a YAML anchor
