apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

images:
  - name: quicklookup/mimir-chat
    newTag: f7d6921

# Production configs reside in the base
resources:
  - ../../base

