remoteWrite:
  - url: "https://ingest.observe.skyvafnir.cloud/api/v1/write"

env:
  - name: VM_remoteWrite_basicAuth_username
    valueFrom:
      secretKeyRef:
        name: observation-basic-auth
        key: username

  - name: VM_remoteWrite_basicAuth_password
    valueFrom:
      secretKeyRef:
        name: observation-basic-auth
        key: password


config:
  scrape_configs:
    - job_name: vmagent
      static_configs:
        - targets: ["localhost:8429"]

    - job_name: postgresql-exporter
      static_configs:
        - targets: ["postgres-exporter-prometheus-postgres-exporter.monitoring.svc:80"]
