images:
  - name: quicklookup/formapi
    newTag: bd7d4a6

resources:
  - ../../base
patches:
  - path: formapi-config.yaml
  - target:
      kind: Ingress
      name: formapi
    patch: |
      - "op": replace
        "path": /spec/rules/0/host
        "value": &fqdn forms-api.contextsuite.dev
      - "op": replace
        "path": /spec/tls/0/hosts/0
        "value": *fqdn  # <- this is a YAML anchor
