apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

images:
  - name: quicklookup/ssp
    newTag: a907d84

resources:
  - ../../base
  - ssp-config.yaml
  - ssp-ingress.yml

patches:
  - path: database-migration.yaml
