apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

configMapGenerator:
  - name: cxs-cube-api-config
    literals:
      - LOG_LEVEL=INFO
      - TABLES_CONFIG_PATH=./cube_schema_config.yaml

resources:
  - cxs-cube-api-deployment.yaml
  - cxs-cube-api-service.yaml

