apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

images:
  - name: quicklookup/cxs-services
    newTag: "4d4f64e"

resources:
  - ../../base

replicas:
  - name: cxsservices
    count: 1
