apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

images:
  - name: quicklookup/mimir-chat
    newTag: 8fed081

configMapGenerator:
  - name: cxs-mimir-web-config
    behavior: merge
    literals:
      - BROWSER_CHAT_API=https://agents.contextsuite.dev
      - BROWSER_APP_API=https://agents.contextsuite.dev
      - MIMIR_SERVER_API=https://agents.contextsuite.dev
      - BROWSER_CHAT_WSS_API=wss://agents.contextsuite.dev
      - NEXT_PUBLIC_APP_URL=https://agents.contextsuite.dev

resources:
  - ../../base

