apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formclient
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  defaultBackend:
    service:
      name: formclient
      port:
        number: 3000
  rules:
    - host: forms.contextsuite.com
      http:
        paths:
          - backend:
              service:
                name: formclient
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - forms.contextsuite.com
      secretName: star-contextsuite-com

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airforms
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  defaultBackend:
    service:
      name: formclient
      port:
        number: 3000
  rules:
    - host: app.airforms.ai
      http:
        paths:
          - backend:
              service:
                name: formclient
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.airforms.ai
      secretName: star-airforms-ai
