apiVersion: v1
kind: ConfigMap
metadata:
  name: formclient-config
data:
  ZONE: 'dev_sbx'

  # Redis
  # REDIS_URL: 'redis-master.data'
  # LOCAL_REDIS: 'true'

  # Required Services
  NEXT_PUBLIC_BACKEND_URL: 'https://forms-staging.contextsuite.com/form-api'