apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solutions

images:
  - name: quicklookup/mimir-api
    newTag: 6709a50

resources:
  - ../../base
  - mimir-api-config.yaml
  - mimir-api-ingress.yml
