# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: azure-gitops-secret
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: azure-store
#     kind: ClusterSecretStore
  
#   target:
#     name: azure-gitops-secret
#     creationPolicy: Owner
#     template:
#       engineVersion: v2
#       data:
#         type: git
#         url: git@ssh.dev.azure.com:v3/skyvafnir/skyvafnir-terraform-modules/skyops
#         sshPrivateKey: |
#           {{ .sshkey }}
#       metadata:
#         labels:
#           argocd.argoproj.io/secret-type: repository

#   data:
#   - secretKey: sshkey
#     remoteRef:
#       key: azure-gitops-key