images:
  - name: quicklookup/gpt-api
    newTag: 2998c0d  # Production tag

resources:
  - ../../base

namespace: solutions

# Production-specific patches
patches:
  - target:
      kind: ConfigMap
      name: gpt-api-config
    patch: |
      - op: replace
        path: /data/ENV
        value: prod
      - op: replace
        path: /data/BACKEND_BASE_URL
        value: https://chat.contextsuite.com
      - op: replace
        path: /data/EVENTS_ENDPOINT
        value: https://in.contextsuite.com/api/s2s/track
  - target:
      kind: Ingress
      name: gpt-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: chat.contextsuite.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: chat.contextsuite.com
      - op: replace
        path: /spec/tls/0/secretName
        value: star-contextsuite-com
  - target:
      kind: HorizontalPodAutoscaler
      name: gpt-api
    patch: |
      - op: replace
        path: /spec/maxReplicas
        value: 4
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/targetCPUUtilizationPercentage
        value: 60