namespace: solutions

configMapGenerator:
  - name: contextsuite-config
    literals:
      - ZONE=dev_sbx
      - REDIS_URL=redis-master.data
      - LOCAL_REDIS=true
      - REACT_APP_GRAPH_API_URL=/graph
      - REACT_APP_CONTEXT_API_ENDPOINT=/context
      - REACT_APP_STATS_API_ENDPOINT=/stats
      - GRAPHQL_SERVER_PORT=4001
      - GRAPHQL_SERVER_PATH=/context
      - WKT_FOLDER=/cdn/wkt_cache
      - REACT_APP_MAPBOX_DARK_TILE_URL=https://api.mapbox.com/styles/v1/ingiatlason/cl4eglwhb000614ld9jgxs50r/tiles/256/{z}/{x}/{y}@2x?access_token=
      - REACT_APP_MAPBOX_LIGHT_TILE_URL=https://api.mapbox.com/styles/v1/ingiatlason/cleie5zek005901pvxxblfo6a/tiles/256/{z}/{x}/{y}@2x?access_token=
      - NEXT_PUBLIC_CONTEXTSUITE_ADMIN_URL=https://admin.contextsuite.com
      - NEXTAUTH_URL=https://app.contextsuite.com
      - SENTRY_ENVIRONMENT=contextsuite-prod
      - NEXT_PUBLIC_SENTRY_DSN=https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160
      - SENTRY_DSN=https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160
      - REACT_APP_CONTEXTSUITE_ADMIN_URL=https://admin.contextsuite.com
      - REACT_APP_JITSU_DEPLOY_DOMAIN=events.contextsuite.com
      - CONTEXTSUITE_ADMIN_URL=https://admin.contextsuite.com
      - NEXT_PUBLIC_CHAT_WSS_ENDPOINT=ws://chat.contextsuite.com:8088/api/table_chat
      - SERVICE_API_URL=http://cxsservices:8088

resources:
  - contextsuite-deployment.yaml
  - contextsuite-service.yaml
  - contextsuite-ingress.yaml
