apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      app: ingress
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress
        tier: api
    spec:
      containers:
      - name: ingress
        image: quicklookup/ingress # Image tag managed in overlays/*/kustomization.yaml
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 2222
          name: sftp
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: NEO4J_PASSWORD
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: REDIS_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_SECRET_KEY
          - name: KAFKA_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: KAFKA_USER_PASSWORD
        envFrom:
          - configMapRef:
              name: ingress-config
        volumeMounts:
          - mountPath: /tmp
            name: sftp
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: sftp
          hostPath:
            path: /data/local/sftp