images:
  - name: quicklookup/contextsuite
    newTag: 632c4fc

configMapGenerator:
  - name: contextsuite-config
    behavior: merge
    literals:
      - SENTRY_ENVIRONMENT=contextsuite-production
      - NEXT_PUBLIC_SENTRY_DSN=""
      - SENTRY_DSN=""
      - NEXTAUTH_URL=https://app.contextsuite.dev
      - REACT_APP_JITSU_DEPLOY_DOMAIN=events.contextsuite.dev
      - CONTEXTSUITE_ADMIN_URL=https://admin.contextsuite.dev
      - NEXT_PUBLIC_CONTEXTSUITE_ADMIN_URL=https://admin.contextsuite.dev
      - NEXT_PUBLIC_CHAT_WSS_ENDPOINT=ws://chat.contextsuite.dev:8088/api/table_chat

resources:
  - ../../base

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: contextsuite
      spec:
        template:
          spec:
            containers:
            - name: node
              env:
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redis-auth
                    key: redis-password
  - target:
      kind: Ingress
      name: contextsuite
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "letsencrypt-prod"
      - op: replace
        path: /spec/tls/0/secretName
        value: "contextsuite-tls"
      - op: replace
        path: /spec/rules/0/host
        value: &fqdn app.contextsuite.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: *fqdn  # <- this is a YAML anchor
